### ISSUE TITLE
New Bid Behavior

### ISSUE THREAD

**Issue by Praetor5426** [10axl/AuctionPlus-Public#2]
Make a config option for enabled/disabled hidden bid behavior

example hidden bids consist of (current behavior)

A diamond sword is currently at $500, player bids $1000, the displayed bid goes up to $510, and when players try to bid it will increase by 10 till the item bid goes over the $1000 bid.

example non-hidden bids consist of

A diamond sword is currently at $500, player bids $1000, the displayed bid goes up to $1000.

**Comment by 10axl** [comment]
Implemented this within the official v1.0.3 release. Please re-open the issue or submit a new issue if you notice issues. :)
