### ISSUE TITLE
Improved not enough money mechanic

### ISSUE THREAD

**Issue by Praetor5426** [10axl/AuctionPlus-Public#3]
When a player no longer has enough money to win the current auction give the item to the next highest bidder instead of essentially canceling the auction.

Example message:
{broke_player} would have won the auction but no longer has enough money! Shame them! {player} has won the auction instead!

**Comment by 10axl** [comment]
Would be quite a bit of a re-work, but I do like the idea, so will keep it in the backlog. Once a milestone or assignee gets added, then this feature will be W.I.P

**Comment by 10axl** [comment]
Should be implemented, please let us know if things seem to not work.
