### ISSUE TITLE
Current bidder increases max bid

### ISSUE THREAD

**Issue by Praetor5426** [10axl/AuctionPlus-Public#6]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am currently winning an auction and would like to raise my max bid, however, I am unable to bid again if I'm currently winning the auction.
**Describe the solution you'd like**
I would like to be able to use /bid command again even if I am winning the auction currently to increase my max bid.
**Describe alternatives you've considered**
No
**Please provide examples if possible**
If applicable, share some examples of the suggestion. [e.g. image, paint, drawing, video, etc...]
![image](https://user-images.githubusercontent.com/30564461/164819550-c4fe2cd3-568e-467d-8c91-c8e558c3f902.png)

**Additional context**

Example scenario

I am currently winning an auction for $500, I would like to increase my bid to $1000. /bid $1000 returns:
"You are already winning this auction but you have increased your max bid to $1000." Instead of "You cannot bid you are already winning this auction."

**Comment by 10axl** [comment]
Completed, should be within v1.0.3, please re-open if it is not working.
